export default {
  "en-GB": { female: "UK English Female", male: "UK English Male" },
  "en-US": { female: "US English Female", male: "US English Male" },
  "es-ES": { female: "Spanish Female", male: "Spanish Male" },
  "fr-FR": { female: "French Female", male: "French Male" },
  "de-DE": { female: "German Female", male: "German Male" },
  "it-IT": { female: "Italian Female", male: "Italian Male" },
  "el-GR": { female: "Greek Female", male: "Greek Male" },
  "hu-HU": { female: "Hungarian Female", male: "Hungarian Male" },
  "tr-TR": { female: "Turkish Female", male: "Turkish Male" },
  "ru-RU": { female: "Russian Female", male: "Russian Male" },
  "nl-NL": { female: "Dutch Female", male: "Dutch Male" },
  "sv-SE": { female: "Swedish Female", male: "Swedish Male" },
  "nb-NO": { female: "Norwegian Female", male: "Norwegian Male" },
  "ja-JP": { female: "Japanese Female", male: "Japanese Male" },
  "ko-KR": { female: "Korean Female", male: "Korean Male" },
  "zh-CN": { female: "Chinese Female", male: "Chinese Male" },
  "en-GB": { female: "UK English Female", male: "UK English Male" },
  "en-US": { female: "US English Female", male: "US English Male" },
  "es-ES": { female: "Spanish Female", male: "Spanish Male" },
  "fr-FR": { female: "French Female", male: "French Male" },
  "de-DE": { female: "German Female", male: "German Male" },
  "it-IT": { female: "Italian Female", male: "Italian Male" },
  "el-GR": { female: "Greek Female", male: "Greek Male" },
  "hu-HU": { female: "Hungarian Female", male: "Hungarian Male" },
  "tr-TR": { female: "Turkish Female", male: "Turkish Male" },
  "ru-RU": { female: "Russian Female", male: "Russian Male" },
  "nl-NL": { female: "Dutch Female", male: "Dutch Male" },
  "sv-SE": { female: "Swedish Female", male: "Swedish Male" },
  "nb-NO": { female: "Norwegian Female", male: "Norwegian Male" },
  "ja-JP": { female: "Japanese Female", male: "Japanese Male" },
  "ko-KR": { female: "Korean Female", male: "Korean Male" },
  "zh-CN": { female: "Chinese Female", male: "Chinese Male" },
  "zh-HK": {
    female: "Chinese (Hong Kong) Female",
    male: "Chinese (Hong Kong) Male",
  },
  "zh-TW": { female: "Chinese Taiwan Female", male: "Chinese Taiwan Male" },
  "hi-IN": { female: "Hindi Female", male: "Hindi Male" },
  "sr-RS": { female: "Serbian Female", male: "Serbian Male" },
  "hr-HR": { female: "Croatian Female", male: "Croatian Male" },
  "bs-BA": { female: "Bosnian Female", male: "Bosnian Male" },
  "ro-RO": { female: "Romanian Female", male: "Romanian Male" },
  "ca-ES": { male: "Catalan Male" },
  "en-AU": { female: "Australian Female", male: "Australian Male" },
  "fi-FI": { female: "Finnish Female", male: "Finnish Male" },
  "af-ZA": { male: "Afrikaans Male" },
  "sq-AL": { male: "Albanian Male" },
  "ar-SA": { female: "Arabic Female", male: "Arabic Male" },
  "hy-AM": { male: "Armenian Male" },
  "cs-CZ": { female: "Czech Female", male: "Czech Male" },
  "da-DK": { female: "Danish Female", male: "Danish Male" },
  eo: { male: "Esperanto Male" },
  "ht-HT": { female: "Haitian Creole Female" },
  "is-IS": { male: "Icelandic Male" },
  "id-ID": { female: "Indonesian Female", male: "Indonesian Male" },
  la: { female: "Latin Female", male: "Latin Male" },
  "lv-LV": { male: "Latvian Male" },
  "mk-MK": { male: "Macedonian Male" },
  "mo-MD": { male: "Moldavian Male" },
  "me-ME": { male: "Montenegrin Male" },
  "pl-PL": { female: "Polish Female", male: "Polish Male" },
  "pt-BR": {
    female: "Brazilian Portuguese Female",
    male: "Brazilian Portuguese Male",
  },
  "pt-PT": { female: "Portuguese Female", male: "Portuguese Male" },
  "sk-SK": { female: "Slovak Female", male: "Slovak Male" },
  "es-LA": {
    female: "Spanish Latin American Female",
    male: "Spanish Latin American Male",
  },
  "sw-KE": { male: "Swahili Male" },
  "ta-IN": { male: "Tamil Male" },
  "th-TH": { female: "Thai Female" },
  "vi-VN": { female: "Vietnamese Female", male: "Vietnamese Male" },
  "cy-GB": { male: "Welsh Male" },
};