```
                                                                             
      ..........                                                                
   ...(%#%(*,......                                          ..                 
  ..,%,.,,,,,*%*,.......                                 .........              
  ..*(,(,...,,*(*((,.......                            ....,,,,,....            
  ..,#,/.......,.,#*/(,.......                      ...,,/#*,,,,*(,.. .         
   .,#*(,....,,,,,.,,(**#,,.......               ....,#*,,,,,..,,%,....         
   ..,(/,..,(,,,,,#*,,,,(//#*,......        .....,*#*,,,*(/,(,.,,#,.. .         
   .../*(,,,(,,(((/,,/*,,,*#*/#*,..............,(*,,,#*.,,,,,(*,**,...          
    ..,#*/,,/,**,(((*#*,(,,,,*(,/#,,........,*#,,,/*,...,.,,*#**(,,...          
    ...,#**,,(,(*//(#//(**(*,,,,(**((,,.,.,(/,,,#,........,,%**%,,...           
     ...,%**,,(*#((#&%///(,,(*,,,,*(,*%**(*,,,/,.........,,%,*#,,...            
      ...,%*/,,/*//(##//*(**,,(,..,,,/,/((,.,/..........,,%,*#,....             
       ...,(*(,,*(*(*(##*/*,*,,(,...,*%*,,/#/,........,,#*,**,....              
        ...,*(/,,,*(,*/((,,,/,.,/,,,,(**(,,#((,.....,,%*,*%,....                
         ....,#*%,,,,(/,,,*%,..,(,,*#,..,(,*,,*#(###/,,,#*.....                 
           ....*(*(,,..,,,,.....(,,%,...../#,.......,*%*.....                   
             ...,*(,(,.........,*,(*,.......//,,,,/#*.....                      
               ....*%*,//,,,,,#,,//....   .............                         
                 ....,*%**,,.,,,%,...                                           
                     ....,,***,....                                             
                         . .                                                    
                                                                                

"I never fail, I learned 10 000 ways that doesn't work!"                                                                                
                                    - Thomas Edison & Me

            Infinisoft World Inc.
            www.infinisoft.world
            info@infinisoft.world
            All rights reserved 2023
```

const iBrainState = require('../src/iBrainState');

describe('iBrainState', () => {
  test('should get and mutate state', () => {
    const initialState = { count: 0 };
    const newState = { count: 1 };
    const stateManager = iBrainState(initialState);

    // Expect initial state to match provided value
    expect(stateManager.getState()).toEqual(initialState);

    // Mutate state
    stateManager.mutate(newState);

    // Expect state to match new value
    expect(stateManager.getState()).toEqual(newState);
  });
});
